### ISSUE TITLE
help connecting to mysql 

### ISSUE THREAD

**Issue by Doxks** [dev-suro/modmail-bot#7]
pass your discord user or server

**Comment by SleepyYui** [comment]
> pass your discord user or server 

you have to input valid MySQL Details in order to make it work

**Comment by Doxks** [comment]
what would be the valid details

**Comment by docimin** [comment]
> what would be the valid details

Hey,

You need to rename _.env to .env and fill in the details.
DATABASE is everything for the MySQL/MariaDB database, make sure to set up your database correctly and fill in the details.

**Comment by Doxks** [comment]
I already did what I don't know is to connect the bot to the database

**Comment by docimin** [comment]
I just told you how to connect the bot to the database. It's via the .env file.
